In [53]:
import numpy as np
from sklearn import preprocessing
from sklearn import decomposition
from sklearn import datasets
from numpy import linalg

In [54]:
X = np.array([[-1, -5], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
print 'X\n', X
print linalg.matrix_rank(X)
U, d, V_T = linalg.svd(X)
n, p = X.shape
number_of_singular_values = len(d)
D = np.concatenate((np.diag(d), np.zeros((n - number_of_singular_values, p))))
rank_low = 1
U_1 =  U[:, 0:rank_low]
D_1 = D[0:rank_low, 0:rank_low]
V_T_1 = V_T[0:rank_low, :]
X_low_rank = np.dot(U_1, np.dot(D_1, V_T_1))
print 'X_low_rank\n', X_low_rank
print linalg.matrix_rank(X_low_rank)

X
[[-1 -5]
 [-2 -1]
 [-3 -2]
 [ 1  1]
 [ 2  1]
 [ 3  2]]
2
X_low_rank
[[-2.87023206 -3.43914855]
 [-1.31304952 -1.57331263]
 [-2.21554175 -2.6546903 ]
 [ 0.90249224  1.08137767]
 [ 1.31304952  1.57331263]
 [ 2.21554175  2.6546903 ]]
1


http://stats.stackexchange.com/questions/134282/relationship-between-svd-and-pca-how-to-use-svd-to-perform-pca

In [55]:
n, p = X.shape
X_centered = preprocessing.scale(X, with_mean=True, with_std=False)
X_centered

array([[-1.        , -4.33333333],
       [-2.        , -0.33333333],
       [-3.        , -1.33333333],
       [ 1.        ,  1.66666667],
       [ 2.        ,  1.66666667],
       [ 3.        ,  2.66666667]])

In [50]:
U, d, V_T = linalg.svd(X_centered)
number_of_singular_values = len(d)
D = np.concatenate((np.diag(d), np.zeros((n - number_of_singular_values, p))))
np.dot(X_centered, V_T)
comps = np.dot(X_centered, V_T)
print comps
print '1st principle component:\n', comps[:,0].reshape(n,1)
var1 = np.var(comps[:,0])
var2 = np.var(comps[:,1])
print 'var1:', var1
print 'var1/(var1+var2):', var1/(var1+var2)

[[-3.90644947  2.12542474]
 [-1.57588084 -1.27581766]
 [-2.98752307 -1.36105977]
 [ 1.91060368 -0.35689126]
 [ 2.57380373  0.39155091]
 [ 3.98544596  0.47679303]]
1st principle component:
[[-3.90644947]
 [-1.57588084]
 [-2.98752307]
 [ 1.91060368]
 [ 2.57380373]
 [ 3.98544596]]
var1: 8.80461558635
var1/(var1+var2): 0.861321089969


sklearn builtin - no need the step to scale to 0 mean - already done in function

In [61]:
pca = decomposition.PCA(n_components=1)
pca.fit(X)
X1_b = pca.transform(X)
print X1_b
print 'explained_variance_', pca.explained_variance_
print 'explained_variance_ratio_', pca.explained_variance_ratio_

[[-3.90644947]
 [-1.57588084]
 [-2.98752307]
 [ 1.91060368]
 [ 2.57380373]
 [ 3.98544596]]
explained_variance_ [ 8.80461559]
explained_variance_ratio_ [ 0.86132109]


In [60]:
np.isclose(X1_b.mean(), 0)

True