See pp.647 of Introduction to Linear Algebra, Fourth Edition 4th Edition by Gilbert Strang

In [25]:
import numpy as np

In [26]:
X = np.array([[1, 2, 3], [4, 5, 6]])

In [27]:
Y = np.array([[7, 8, 9], [10, 11, 12]])

In [28]:
X.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
Y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [34]:
prdct = np.dot(X.T, Y)

In [41]:
prdct

array([[47, 52, 57],
       [64, 71, 78],
       [81, 90, 99]])

In [35]:
np.trace(prdct)

217

In [37]:
m, n = X.shape

In [38]:
ip = 0

In [39]:
for i in range(m):
    for j in range(n):
        ip += X[i,j] * Y[i,j]

In [40]:
ip

217

In [44]:
x = X.flatten()
y = Y.flatten()

In [45]:
np.dot(x.T, y)

217